### ISSUE TITLE
Problemas con Dom by ID

### ISSUE THREAD

**Issue by acanivano** [CarlosHerrera4/Seminario_Dojo#3]
Hola Carlos. Tengo un problema con este código. Quiero obtener el valor de este menú desplegable cuando se elija una de estas opciones por medio de un event de onChange; posteriormente lo pasaría dentro de una query para hacer una Feature Layer y mostrarlo en mi visor.

`<select name="select1" data-dojo-type="dijit/form/Select" id="select>
            <option value="Artesania">Artesania</option>
            <option value="Banco" selected="selected">Banco</option>
            <option value="Bar">Bar</option>
            <option value="Bodega">Bodega</option>`

Y lo estoy llamando así:

`var SeleccLocal = dom.byId("select").value;`

El problema es que me dice que el valor es "null" llamado al id del selector; no sñe si tendría que llamar al name o al id.
¿Se te ocurre alguna idea? Gracias

**Comment by acanivano** [comment]
Vale, ya lo he solucionado así:
`var SeleccLocal = document.getElementById('select').value;
            SeleccLocal.addEventListener('change', function(){
            console.log(this.value);});`

Ahora tengo un problema algo tonto; este script me funciona si lo pongo en el html después del select; pero si lo pongo en el script externo al html, la console.log me dice que está null. 
¿Dónde debería ponerlo?

**Comment by CarlosHerrera4** [comment]
Hola Alberto. Por partes: 

- Es probable que el el script te funcione sólo si está colocado después del select debido a que no tendrás esta línea en tu código antes de colocar el CDN de Dojo.
`	<script>dojoConfig = {async: true, parseOnLoad: false}</script>`
Lo que realiza es que convierte tus dijits (widgets) en nodos para que puedan ser renderizados correctamente aunque no se haya cargado el CDN de Dojo completamente.

- Échale un vistazo a este ejemplo [https://github.com/MundoGister/Seminario_Dojo/blob/gh-pages/example_domById.html](https://github.com/MundoGister/Seminario_Dojo/blob/gh-pages/example_domById.html). Está basado en tu código y simplificado. Está a la escucha de que cuande el elemento del `<select>` cambie, muestre debajo el elemento seleccionado. Lo importante es que  una vez tengas el valor, puedes hacer lo que quieras con él (en tu caso, pasarlo a una query). Pruébalo para ver si te puede servir y me cuentas. (Ejemplo en funcionamiento [aquí](https://mundogister.github.io/Seminario_Dojo/example_domById.html))

**Comment by acanivano** [comment]
Gracias por tu respuesta Carlos!
He colgado el código en mi repositorio y te he comentado una cosa
