### ISSUE TITLE
data-dojo-attach-point

### ISSUE THREAD

**Issue by acanivano** [CarlosHerrera4/Seminario_Dojo#4]
Hola Carlos. Tengo un problema con la conexión entre el widget.html y widget.js.

```
   <div>

      <strong>Poblacion total: </strong><span class="stats" data-dojo-attach-point="pobtot"></span><br>
      <strong>Menos de 15 años: </strong><span class="stats" data-dojo-attach-point="menos15"></span><br>
      <strong>Entre 16 y 64 años: </strong><span class="stats" data-dojo-attach-point="entre16_64"></span><br>
      <strong>Mas de 65 años: </strong><span class="stats" data-dojo-attach-point="mas65"></span><br>
      
    </div>>
```
Y esta la función callback del widget.js
```
 function show(results){
       var stats = results.features[0].attributes;
      this.pobtot.innerHTML = stats.Sum_POB_TOT + " habitantes";
      this.menos15.innerHTML = stats.Sum_EDAD0015 + " habitantes";
      this.entre16_64.innerHTML = stats.Sum_EDAD1664 + " habitantes";
      this.mas65.innerHTML = stats.Sum_EDAD65_ + " habitantes";
  };

```
El caso que la variable Stats me devuelve datos pero me da error "TypeError: Cannot set property 'innerHTML' of undefined"
Entiendo que está siendo un problema de sintaxis, supongo que estaré metiendo la zarpa en algo, pero no lo veo. ¿le podrías echar un vistazo? Gracias

**Comment by CarlosHerrera4** [comment]
Entiendo que `function show(results) { ... }` está dentro de `onOpen: function() { ... }`. Dentro de function show, this hace referencia a otro ámbito, por eso no reconoce `this.pobtot`, `this.menos15`, etc. Para ello debes declarar una `var example = this` justo antes de entrar a `function show(results) { ... }` , y dentro de la función sustituye `this` por la variable `example` (`example.pobtot`, `example.menos15` ...).

Prueba y me dices.

**Comment by acanivano** [comment]
Genial, tenía problemas con los ámbitos. Funcionando; gracias!
