### ISSUE TITLE
Enventos en dojo

### ISSUE THREAD

**Issue by acanivano** [CarlosHerrera4/Seminario_Dojo#5]
Hola Carlos. Estoy ahora liado con otro widget cuyo objetivo (tengo que valorar si se podría hacer mejor off-panel) es que el usuario pase el cursor sobre una capa de polígonos y cada polígono se ilumine y enseñe un infotemplate con datos sobre el valor del suelo. Tengo este código hecho, que en javascript funciona correctamente:
```
define(['dojo/_base/declare',
'jimu/BaseWidget',
  "dojo/dom",
  "dojo/dom-class",
  "dojo/on",
  "esri/layers/FeatureLayer",
  'esri/renderers/SimpleRenderer',
  "esri/map", 
  "dojo/store/Memory",
  "esri/InfoTemplate",
  "esri/graphic",
  "esri/symbols/SimpleLineSymbol",
  "esri/symbols/SimpleFillSymbol",
  "esri/Color",
  "dijit/form/FilteringSelect",
  "dojo/mouse",
  "dojo/_base/lang",
  "dojo/domReady!"],

function(
declare,
 BaseWidget,
 dom,
 domClass,
 on,
 FeatureLayer,
 SimpleRenderer,
 Map,
 Memory,
 InfoTemplate,
 Graphic,
 SimpleLineSymbol,
 SimpleFillSymbol,
 Color,
 FilteringSelect,
 mouse,
 lang) {
  
  return declare([BaseWidget], {
    
    baseClass: 'jimu-widget-demo',
    name: "editando",
    symbol: null,
    Tarifazonas :"https://localhost:6443/arcgis/rest/services/Emprendedores_/Emprendedores_/MapServer/3",

    postCreate: function() {
       this.symbol = new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID,
          new SimpleLineSymbol(
            SimpleLineSymbol.STYLE_SOLID,
            new Color([255,0,0]), 3
          ),
          new Color([125,125,125,0.35])
        );
    },

    startup: function() {},


    onOpen: function(){

      this.map.on("mouse-over", lang.hitch (this, function(evt){
        
        var map = this.map;
        var symbol = this.symbol;
        var content = this.content;
        var infoTemplate = this.infoTemplate;
        var ZonasTarifa = this.Tarifazonas;
        var highlightGraphic = this.highlightGraphic;
       
        var content = "<b>Precio</b>: ${Precio}" +
                      "<br><b>Poblacion</b>" +
                      "<br><b>Locales varios</b>:";

        var infoTemplate = new InfoTemplate();
          infoTemplate.setTitle("${zona}")
          infoTemplate.setContent(content);

        var ZonasTarifa = new FeatureLayer(ZonasTarifa, {
          mode: FeatureLayer.MODE_SNAPSHOT,
          infoTemplate: infoTemplate,
          outFields: ["Precio"]
        }); 
             
        var highlightGraphic = new Graphic(evt.graphic.geometry,symbol);
        map.graphics.add(highlightGraphic);
      })); //Mouse Over
     
    },//ON OPEN

    onClose: function(){},
   
  });
});
```
Al adaptarlo al Widget.js, devolver, devuelve valores pero cuando llega a Geometry el código peta (undefined); estoy teniendo problemas de contexto segurísimo; pero no consigo verlo.
Por lo que he estado leyendo, mouse-over es el evento que tengo que usar pero, ¿cómo sabe el programa que le quiero pasar sólo la geometría de la entidad? porque tal como está escrito creo que estoy haciéndolo sobre la extensión de todo el mapa.
No sé si en lugar de este código debería usar 
`dojo.connect(nombre_entidad, "mouse-over",  function(newValue){lo que sea})`
Gracias por tu ayuda Carlos

**Comment by CarlosHerrera4** [comment]
Sólo quieres que se muestre el infoTemplate y se ilumine al pasar por la FeatureLayer (`var ZonasTarifa`), para ello debes tener un evento listener sobre dicho elemento. En tu caso lo tienes colocado en el map (`this.map.on("mouse-over", lang.hitch (this, function(evt){... `  ). Para que esté a la escucha deberías poner  `ZonasTarifa.on( "mouse-over", function (evt) { ... } )`. De este modo sólo al pasar por la geometría de tu FeatureLayer realizará la acción que quieras. También debes tener en cuenta que en este caso deberías colocar también otro evento "`mouse-out`" para cuando el ratón salga de la capa.

**Comment by acanivano** [comment]
Buenas Carlos. Precisamente ayer encontré un widget que tienes publicado en el repositorio Widgets_Web_AppBuilder que hace precisamente lo que buscaba. Es el de FeatureLayer Hover.
El caso es que no me funcionaba y le he tenido que añadir una línea de código para que destruyera la id que crea cada vez que pasas el cursor por la capa. (me daba ese fallo el navegador)
Querría usarlo para mi proyecto como widget, te citaría y pondría el cambio que he hecho. ¿Te importa? Cuando presente, te hago un fork y ya aprendo como se hace , que nunca lo he hecho

**Comment by CarlosHerrera4** [comment]
Cierto. Tuve que cambiar ese apartado y no volví a subir el widget. Lo actualizaré. Lo que hice en mi caso era que creara un id aleatorio cada vez, pero en el fondo es lo mismo. Puedes utilizarlo ya que por eso lo subí a GitHub y al repositorio de widgets de Esri (http://esri-es.github.io/Web-AppBuilder-Custom-Widgets/), pero ten en cuenta que yo lo utilicé para mi proyecto también (por si te ponen pegas). Mi consejo si lo utilizas es que lo personalices y (si tienes tiempo xD) mejorarlo.

**Comment by acanivano** [comment]
Bueno, ya poco tiempo nos queda; intentaré modificar un poco el estilo y lo que se me ocurra.
Cuando pase por la ofi te saludo. Gracias!
